<?php

declare(strict_types=1);

namespace NeNeConcierge\Session;

/**
 * Represents a visitor's chat session traversing a published scenario.
 *
 * The primary key is a UUID string (CHAR(36)) generated by the application,
 * not an auto-increment integer, so that session IDs are shareable in public
 * embed widget URLs without leaking row counts.
 *
 * variables holds key→value pairs collected from visitor answers at
 * message nodes with data.collect_variable set.
 * outcome = 'preview' marks ephemeral admin preview sessions that are
 * excluded from analytics queries.
 */
final readonly class ChatSession
{
    /**
     * @param array<string, string> $variables
     */
    public function __construct(
        public string         $id,
        public int            $organizationId,
        public int            $scenarioId,
        public ?string        $currentNodeId,
        public SessionOutcome $outcome,
        public bool           $hasConversion,
        public string         $startedAt,
        public array          $variables = [],
        public ?string        $endedAt   = null,
    ) {
    }
}
