<?php

declare(strict_types=1);

namespace NeNeConcierge\Session;

/**
 * Represents a visitor's chat session traversing a published scenario.
 *
 * The primary key is a UUID string (CHAR(36)) generated by the application,
 * not an auto-increment integer, so that session IDs are shareable in public
 * embed widget URLs without leaking row counts.
 */
final readonly class ChatSession
{
    public function __construct(
        public string         $id,
        public int            $organizationId,
        public int            $scenarioId,
        public ?string        $currentNodeId,
        public SessionOutcome $outcome,
        public bool           $hasConversion,
        public string         $startedAt,
        public ?string        $endedAt = null,
    ) {
    }
}
